name: Deploy Dia 22 (develop -> main)
on:
  schedule:
    # 23:59 BRT do dia 22 = 02:59 UTC do dia 23
    - cron: '59 02 23 12 *'
jobs:
  merge-dia-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch origin develop
          git checkout main
          git merge origin/develop --no-ff -m "Auto-Deploy Post 05"
          git push origin main