name: Deploy Dia 24 (Natal -> Main)
on:
  schedule:
    # 23:59 BRT do dia 24 = 02:59 UTC do dia 25
    - cron: '59 02 25 12 *'
jobs:
  merge-dia-24:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git fetch origin release-natal-06
          git checkout main
          git merge origin/release-natal-06 --no-ff -m "Auto-Deploy Post 06"
          git push origin main